apiVersion: v1
entries:
  alloy:
  - apiVersion: v2
    appVersion: v1.1.0
    created: "2024-06-07T16:54:19.781916-04:00"
    dependencies:
    - condition: crds.create
      name: crds
      repository: ""
      version: 0.0.0
    description: Grafana Alloy
    digest: d772a791726ba1646bc443e802f9a2fef9b08e82081b800da2f6d72478248cdf
    icon: https://raw.githubusercontent.com/grafana/alloy/main/docs/sources/assets/alloy_icon_orange.svg
    name: alloy
    type: application
    urls:
    - charts/alloy-0.3.1.tgz
    version: 0.3.1
  k8s-monitoring:
  - apiVersion: v2
    appVersion: 2.3.1
    created: "2024-06-07T16:54:19.781068-04:00"
    dependencies:
    - name: alloy
      repository: https://grafana.github.io/helm-charts
      version: 0.3.1
    - alias: alloy-events
      condition: logs.cluster_events.enabled
      name: alloy
      repository: https://grafana.github.io/helm-charts
      version: 0.3.1
    - alias: alloy-logs
      condition: logs.pod_logs.enabled
      name: alloy
      repository: https://grafana.github.io/helm-charts
      version: 0.3.1
    - alias: alloy-profiles
      condition: profiles.enabled
      name: alloy
      repository: https://grafana.github.io/helm-charts
      version: 0.3.1
    - condition: kube-state-metrics.enabled
      name: kube-state-metrics
      repository: https://prometheus-community.github.io/helm-charts
      version: 5.19.0
    - condition: prometheus-node-exporter.enabled
      name: prometheus-node-exporter
      repository: https://prometheus-community.github.io/helm-charts
      version: 4.34.0
    - condition: prometheus-operator-crds.enabled
      name: prometheus-operator-crds
      repository: https://prometheus-community.github.io/helm-charts
      version: 11.0.0
    - condition: prometheus-windows-exporter.enabled
      name: prometheus-windows-exporter
      repository: https://prometheus-community.github.io/helm-charts
      version: 0.3.1
    - condition: opencost.enabled
      name: opencost
      repository: https://opencost.github.io/opencost-helm-chart
      version: 1.35.0
    description: A Helm chart for gathering, scraping, and forwarding Kubernetes telemetry
      data to a Grafana Stack.
    digest: 1a907c52494ee20d8911eb82edfc486fb95a47b42f0b4490b0ccb08a2764b6bb
    icon: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg
    maintainers:
    - email: pete.wall@grafana.com
      name: petewall
    - email: stephen.lang@grafana.com
      name: skl
    name: k8s-monitoring
    sources:
    - https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring
    type: application
    urls:
    - k8s-monitoring-1.0.12.tgz
    version: 1.0.12
  kube-state-metrics:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/prometheus-community/helm-charts
    apiVersion: v2
    appVersion: 2.12.0
    created: "2024-06-07T16:54:19.782619-04:00"
    description: Install kube-state-metrics to generate and expose cluster-level metrics
    digest: 3be4e99851d3c05a3b186f4852d0620852c1a1247710b13256abb63aff4f35e2
    home: https://github.com/kubernetes/kube-state-metrics/
    keywords:
    - metric
    - monitoring
    - prometheus
    - kubernetes
    maintainers:
    - email: tariq.ibrahim@mulesoft.com
      name: tariq1890
    - email: manuel@rueg.eu
      name: mrueg
    - email: david@0xdc.me
      name: dotdc
    name: kube-state-metrics
    sources:
    - https://github.com/kubernetes/kube-state-metrics/
    type: application
    urls:
    - charts/kube-state-metrics-5.19.0.tgz
    version: 5.19.0
  opencost:
  - apiVersion: v2
    appVersion: 1.110.0
    created: "2024-06-07T16:54:19.78344-04:00"
    description: OpenCost and OpenCost UI
    digest: 70a42b57ae50f38a0e5b7ca10956fc36afecf8d4e6a67d4467cc99fbdfe269cf
    home: https://github.com/opencost/opencost-helm-chart
    keywords:
    - cloud-costs
    - cost-optimization
    - finops
    - monitoring
    - opencost
    maintainers:
    - name: mattray
      url: https://mattray.dev
    - name: toscott
    - email: rafa@stormforge.io
      name: brito-rafa
    name: opencost
    type: application
    urls:
    - charts/opencost-1.35.0.tgz
    version: 1.35.0
  prometheus-node-exporter:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/prometheus-community/helm-charts
    apiVersion: v2
    appVersion: 1.8.0
    created: "2024-06-07T16:54:19.784173-04:00"
    description: A Helm chart for prometheus node-exporter
    digest: 75cdcb0d989ba242753278166af00310f483147c189f231e5887e7efe410ca3c
    home: https://github.com/prometheus/node_exporter/
    keywords:
    - node-exporter
    - prometheus
    - exporter
    maintainers:
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: zanhsieh@gmail.com
      name: zanhsieh
    - email: rootsandtrees@posteo.de
      name: zeritti
    name: prometheus-node-exporter
    sources:
    - https://github.com/prometheus/node_exporter/
    type: application
    urls:
    - charts/prometheus-node-exporter-4.34.0.tgz
    version: 4.34.0
  prometheus-operator-crds:
  - annotations:
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/prometheus-community/helm-charts
      artifacthub.io/maintainers: |
        - name: dacamposol
          email: dacamposol@gmail.com
        - name: desaintmartin
          email: cedric@desaintmartin.fr
        - name: QuentinBisson
          email: quentin.bisson@gmail.com
    apiVersion: v2
    appVersion: v0.73.0
    created: "2024-06-07T16:54:19.790428-04:00"
    dependencies:
    - name: crds
      repository: ""
      version: 0.0.0
    description: 'A Helm chart that collects custom resource definitions (CRDs) from
      the Prometheus Operator, allowing for seamless integration with GitOps tools '
    digest: a7ca9754039775801aaa6e55bc9e2f6fe4ab3ce24e9435509281614f0569f34c
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    keywords:
    - prometheus
    - crds
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: dacamposol@gmail.com
      name: dacamposol
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    - email: quentin.bisson@gmail.com
      name: QuentinBisson
    - email: github@jkroepke.de
      name: jkroepke
    name: prometheus-operator-crds
    sources:
    - https://github.com/prometheus-community/helm-charts
    type: application
    urls:
    - charts/prometheus-operator-crds-11.0.0.tgz
    version: 11.0.0
  prometheus-windows-exporter:
  - apiVersion: v2
    appVersion: 0.25.1
    created: "2024-06-07T16:54:19.790967-04:00"
    description: A Helm chart for prometheus windows-exporter
    digest: 5067b9073422849a5aa8283fa31730beb856443873a578bd81d86165bd0f27f7
    home: https://github.com/prometheus-community/windows_exporter/
    keywords:
    - windows-exporter
    - windows
    - prometheus
    - exporter
    maintainers:
    - email: github@jkroepke.de
      name: jkroepke
    name: prometheus-windows-exporter
    sources:
    - https://github.com/prometheus-community/windows_exporter/
    type: application
    urls:
    - charts/prometheus-windows-exporter-0.3.1.tgz
    version: 0.3.1
generated: "2024-06-07T16:54:19.766939-04:00"
