apiVersion: v1
entries:
  k8s-monitoring:
  - apiVersion: v2
    appVersion: 2.3.1
    created: "2024-06-10T10:00:09.971219-04:00"
    dependencies:
    - name: alloy
      repository: https://grafana.github.io/helm-charts
      version: 0.3.1
    - alias: alloy-events
      condition: logs.cluster_events.enabled
      name: alloy
      repository: https://grafana.github.io/helm-charts
      version: 0.3.1
    - alias: alloy-logs
      condition: logs.pod_logs.enabled
      name: alloy
      repository: https://grafana.github.io/helm-charts
      version: 0.3.1
    - alias: alloy-profiles
      condition: profiles.enabled
      name: alloy
      repository: https://grafana.github.io/helm-charts
      version: 0.3.1
    - condition: kube-state-metrics.enabled
      name: kube-state-metrics
      repository: https://prometheus-community.github.io/helm-charts
      version: 5.19.0
    - condition: prometheus-node-exporter.enabled
      name: prometheus-node-exporter
      repository: https://prometheus-community.github.io/helm-charts
      version: 4.34.0
    - condition: prometheus-operator-crds.enabled
      name: prometheus-operator-crds
      repository: https://prometheus-community.github.io/helm-charts
      version: 11.0.0
    - condition: prometheus-windows-exporter.enabled
      name: prometheus-windows-exporter
      repository: https://prometheus-community.github.io/helm-charts
      version: 0.3.1
    - condition: opencost.enabled
      name: opencost
      repository: https://opencost.github.io/opencost-helm-chart
      version: 1.35.0
    description: A Modified chart by pavilionpay to use a APIM key header.
    digest: 94ad3f201860dc1a268c34d0a39a9a34208cc7a85eadadcfb4cd45a611dede62
    icon: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg
    maintainers:
    - email: pete.wall@grafana.com
      name: petewall
    - email: stephen.lang@grafana.com
      name: skl
    name: k8s-monitoring
    sources:
    - https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring
    type: application
    urls:
    - k8s-monitoring-1.0.12.tgz
    version: 1.0.12
generated: "2024-06-10T10:00:09.944293-04:00"
