apiVersion: v1
entries:
  k8s-monitoring:
  - apiVersion: v2
    appVersion: 2.8.1
    created: "2024-09-12T07:52:34.893379-04:00"
    dependencies:
    - condition: alloy.enabled
      name: alloy
      repository: https://grafana.github.io/helm-charts
      version: 0.7.0
    - alias: alloy-events
      condition: logs.enabled, logs.cluster_events.enabled
      name: alloy
      repository: https://grafana.github.io/helm-charts
      version: 0.7.0
    - alias: alloy-logs
      condition: logs.enabled, logs.pod_logs.enabled
      name: alloy
      repository: https://grafana.github.io/helm-charts
      version: 0.7.0
    - alias: alloy-profiles
      condition: profiles.enabled
      name: alloy
      repository: https://grafana.github.io/helm-charts
      version: 0.7.0
    - condition: kube-state-metrics.enabled
      name: kube-state-metrics
      repository: https://prometheus-community.github.io/helm-charts
      version: 5.25.1
    - condition: prometheus-node-exporter.enabled
      name: prometheus-node-exporter
      repository: https://prometheus-community.github.io/helm-charts
      version: 4.39.0
    - condition: prometheus-operator-crds.enabled
      name: prometheus-operator-crds
      repository: https://prometheus-community.github.io/helm-charts
      version: 14.0.0
    - condition: prometheus-windows-exporter.enabled
      name: prometheus-windows-exporter
      repository: https://prometheus-community.github.io/helm-charts
      version: 0.6.0
    - condition: opencost.enabled
      name: opencost
      repository: https://opencost.github.io/opencost-helm-chart
      version: 1.42.0
    - condition: kepler.enabled
      name: kepler
      repository: https://sustainable-computing-io.github.io/kepler-helm-chart
      version: 0.5.9
    - condition: beyla.enabled
      name: beyla
      repository: https://grafana.github.io/helm-charts
      version: 1.4.0
    description: forked for pavilion. A Helm chart for gathering, scraping, and forwarding
      Kubernetes telemetry data to a Grafana Stack.
    digest: 5e95f1c4cd6e5450995a4ad79fd1ece20db0fc5a6abf4512aacc625f2ebecc21
    icon: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg
    maintainers:
    - email: pete.wall@grafana.com
      name: petewall
    - email: stephen.lang@grafana.com
      name: skl
    name: k8s-monitoring
    sources:
    - https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring
    type: application
    urls:
    - k8s-monitoring-1.5.12.tgz
    version: 1.5.12
generated: "2024-09-12T07:52:34.875383-04:00"
